name: Run manually

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      MY_ENV: 'Environment variable value'
      API_LINK: '${{github.api_url}}'
    steps:
      - name: List_job
        run: echo '${{ toJSON(job)}}'
      - name: List_runner
        run: echo '${{ toJSON(runner)}}'
      - name: List_ENV
        run: echo '${{ toJSON(env)}}'
      - name: List_github
        run: echo '${{ toJSON(github)}}'
