name: CI Build for Docker Action
on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run my own container action
        id: hello-action
        uses: ps-actions-sandbox/rulasg-action-demo@v1
        with:
          who-to-greet: '@rulasg'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
